local MAX_PROJECTILES_PER_CAST_DEFAULT = 32
local MAX_PROJECTILES_PER_CAST_CHAOS = 64
local MAX_PROJECTILES_PER_CAST_HARD = 96

local MAX_PAYLOAD_FANOUT_DEFAULT = 8
local MAX_PAYLOAD_FANOUT_CHAOS = 16
local MAX_PAYLOAD_FANOUT_HARD = 32

local MAX_NESTED_FINAL_FANOUT_DEFAULT = 8
local MAX_NESTED_FINAL_FANOUT_CHAOS = 16
local MAX_NESTED_FINAL_FANOUT_HARD = 32

local MAX_CAST_TOTAL_JOB_BUDGET_DEFAULT = 32
local MAX_CAST_TOTAL_JOB_BUDGET_CHAOS = 64
local MAX_CAST_TOTAL_JOB_BUDGET_HARD = 96

local MAX_JOBS_PER_TICK_DEFAULT = 16
local MAX_JOBS_PER_TICK_CHAOS = 24
local MAX_LIVE_LAUNCHES_PER_TICK_DEFAULT = 8
local MAX_LIVE_LAUNCHES_PER_TICK_CHAOS = 4

local MAX_NESTED_PAYLOAD_JOBS_DEFAULT = 32
local MAX_NESTED_PAYLOAD_JOBS_CHAOS = 64

local MAX_CHAIN_HOPS_DEFAULT = 5
local MAX_CHAIN_HOPS_CHAOS = 5
local MAX_CHAIN_BRANCHES_DEFAULT = 1
local MAX_CHAIN_BRANCHES_CHAOS = 1
local MAX_CHAIN_SCAN_CANDIDATES_DEFAULT = 16
local MAX_CHAIN_SCAN_CANDIDATES_CHAOS = 24

local limits = {
    MAX_RECURSION_DEPTH = 3,
    MAX_PROJECTILES_PER_CAST_DEFAULT = MAX_PROJECTILES_PER_CAST_DEFAULT,
    MAX_PROJECTILES_PER_CAST_CHAOS = MAX_PROJECTILES_PER_CAST_CHAOS,
    MAX_PROJECTILES_PER_CAST_HARD = MAX_PROJECTILES_PER_CAST_HARD,
    MAX_PROJECTILES_PER_CAST = MAX_PROJECTILES_PER_CAST_DEFAULT,
    MAX_SCAN_RADIUS = 2048,

    MAX_PAYLOAD_FANOUT_DEFAULT = MAX_PAYLOAD_FANOUT_DEFAULT,
    MAX_PAYLOAD_FANOUT_CHAOS = MAX_PAYLOAD_FANOUT_CHAOS,
    MAX_PAYLOAD_FANOUT_HARD = MAX_PAYLOAD_FANOUT_HARD,
    MAX_PAYLOAD_FANOUT = MAX_PAYLOAD_FANOUT_DEFAULT,
    MAX_NESTED_FINAL_FANOUT_DEFAULT = MAX_NESTED_FINAL_FANOUT_DEFAULT,
    MAX_NESTED_FINAL_FANOUT_CHAOS = MAX_NESTED_FINAL_FANOUT_CHAOS,
    MAX_NESTED_FINAL_FANOUT_HARD = MAX_NESTED_FINAL_FANOUT_HARD,
    MAX_NESTED_FINAL_FANOUT = MAX_NESTED_FINAL_FANOUT_DEFAULT,
    MAX_CAST_TOTAL_JOB_BUDGET_DEFAULT = MAX_CAST_TOTAL_JOB_BUDGET_DEFAULT,
    MAX_CAST_TOTAL_JOB_BUDGET_CHAOS = MAX_CAST_TOTAL_JOB_BUDGET_CHAOS,
    MAX_CAST_TOTAL_JOB_BUDGET_HARD = MAX_CAST_TOTAL_JOB_BUDGET_HARD,
    MAX_CAST_TOTAL_JOB_BUDGET = MAX_CAST_TOTAL_JOB_BUDGET_DEFAULT,

    MAX_CHAIN_HOPS_DEFAULT = MAX_CHAIN_HOPS_DEFAULT,
    MAX_CHAIN_HOPS_CHAOS = MAX_CHAIN_HOPS_CHAOS,
    MAX_CHAIN_HOPS = MAX_CHAIN_HOPS_DEFAULT,
    MAX_CHAIN_AUDIT_HOPS = MAX_CHAIN_HOPS_DEFAULT,
    MAX_CHAIN_TARGETS_PER_HOP = 1,
    MAX_CHAIN_SCAN_RADIUS = 1024,
    MAX_CHAIN_SCAN_CANDIDATES_DEFAULT = MAX_CHAIN_SCAN_CANDIDATES_DEFAULT,
    MAX_CHAIN_SCAN_CANDIDATES_CHAOS = MAX_CHAIN_SCAN_CANDIDATES_CHAOS,
    MAX_CHAIN_SCAN_CANDIDATES = MAX_CHAIN_SCAN_CANDIDATES_DEFAULT,
    MAX_CHAIN_VERTICAL_DELTA = 64,
    CHAIN_AIM_HEIGHT = 96,
    MAX_CHAIN_JOBS_PER_CAST = MAX_CHAIN_HOPS_DEFAULT,
    MAX_CHAIN_BRANCHES_DEFAULT = MAX_CHAIN_BRANCHES_DEFAULT,
    MAX_CHAIN_BRANCHES_CHAOS = MAX_CHAIN_BRANCHES_CHAOS,
    MAX_CHAIN_BRANCHES = MAX_CHAIN_BRANCHES_DEFAULT,

    MAX_JOBS_PER_TICK_DEFAULT = MAX_JOBS_PER_TICK_DEFAULT,
    MAX_JOBS_PER_TICK_CHAOS = MAX_JOBS_PER_TICK_CHAOS,
    MAX_JOBS_PER_TICK = MAX_JOBS_PER_TICK_DEFAULT,
    MAX_LIVE_LAUNCHES_PER_TICK_DEFAULT = MAX_LIVE_LAUNCHES_PER_TICK_DEFAULT,
    MAX_LIVE_LAUNCHES_PER_TICK_CHAOS = MAX_LIVE_LAUNCHES_PER_TICK_CHAOS,
    MAX_LIVE_LAUNCHES_PER_TICK = MAX_LIVE_LAUNCHES_PER_TICK_DEFAULT,
    MAX_NESTED_PAYLOAD_JOBS_DEFAULT = MAX_NESTED_PAYLOAD_JOBS_DEFAULT,
    MAX_NESTED_PAYLOAD_JOBS_CHAOS = MAX_NESTED_PAYLOAD_JOBS_CHAOS,
    MAX_NESTED_PAYLOAD_JOBS = MAX_NESTED_PAYLOAD_JOBS_DEFAULT,
    MAX_NESTED_PAYLOAD_DEPTH = 3,
    MAX_NESTED_PAYLOAD_FANOUT = MAX_PAYLOAD_FANOUT_DEFAULT,
}

return limits
